package com.ninjaone.dundie_awards.event;

public enum EventType {
    AWARD_ORGANIZATION_SUCCESS_EVENT,
    SAVE_ACTIVITY_AWARD_ORGANIZATION_SUCCESS_EVENT,
    SAVE_ACTIVITY_AWARD_ORGANIZATION_RETRY_EVENT,
    SAVE_ACTIVITY_AWARD_ORGANIZATION_FAILURE_EVENT,
    UNBLOCK_ORGANIZATION_SUCCESS_EVENT,
    UNBLOCK_ORGANIZATION_RETRY_EVENT,
    UNBLOCK_ORGANIZATION_FAILURE_EVENT,
    AWARD_ORGANIZATION_ROLLBACK_SUCCESS_EVENT,
    AWARD_ORGANIZATION_ROLLBACK_RETRY_EVENT,
    AWARD_ORGANIZATION_ROLLBACK_FAILURE_EVENT;
}

